apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: opensearch-logstash
  name: opensearch-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch-logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/test-default: "true"
        io.kompose.service: opensearch-logstash
    spec:
      containers:
        - args:
            - -f
            - /usr/share/logstash/config/pipeline.conf
          env:
            - name: LOGSTASH_INTERNAL_PASSWORD
              value: ${LOGSTASH_INTERNAL_PASSWORD:-}
            - name: LS_JAVA_OPTS
              value: -Xmx256m -Xms256m
          image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.4.0
          name: opensearch-logstash
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config/pipeline.conf
              name: opensearch-logstash-hostpath0
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/xtrray/opensearch/test/pipeline.conf
          name: opensearch-logstash-hostpath0
status: {}
