apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: opensearch-node2
  name: opensearch-node2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opensearch-node2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/test-default: "true"
        io.kompose.service: opensearch-node2
    spec:
      containers:
        - env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.initial_cluster_manager_nodes
              value: opensearch-node1,opensearch-node2
            - name: cluster.name
              value: opensearch-cluster
            - name: discovery.seed_hosts
              value: opensearch-node1,opensearch-node2
            - name: node.name
              value: opensearch-node2
          image: opensearchproject/opensearch:2.4.0
          name: opensearch-node2
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-data2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/xtrray/opensearch/test
          name: opensearch-data2
status: {}
