apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: opensearch-node
  name: opensearch-node
spec:
  serviceName: opensearch-node-service
  replicas: 2
  selector:
    matchLabels:
      app: opensearch-node
  template:
    metadata:
      labels:
        app: opensearch-node
    spec:
      containers:
        - env:
            - name: OPENSEARCH_JAVA_OPTS
              value: -Xms512m -Xmx512m
            - name: bootstrap.memory_lock
              value: "true"
            - name: cluster.initial_cluster_manager_nodes
              value: "opensearch-node-0,opensearch-node-1"
            - name: cluster.name
              value: opensearch-cluster
            - name: discovery.seed_hosts
              value: "opensearch-node-0.opensearch-node,opensearch-node-1.opensearch-node"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: opensearchproject/opensearch:2.4.0
          name: opensearch-node
  #        securityContext:
   #         privileged: true
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/opensearch/data
              name: opensearch-data
            - mountPath: /etc/systemd/system/opensearch.service.d/override.conf
              name: memlock-config
      initContainers:
        - name: fix-permissions
          image: busybox
          command: 
          - sh
          - -c
          - "chown -R 1000:1000 /usr/share/opensearch/data"
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
          - name: opensearch-data
            mountPath: /usr/share/opensearch/data
        - name: init-sysctl
          image: busybox
          command:
          - sh
          - -c
          - "while true; do mmc=$(cat /proc/sys/vm/max_map_count); if [ ${mmc} -eq 262144 ]; then exit 0; fi; sleep 1; done"
#          - "systemctl -w vm.max_map_count=262144  && timedatectl set-local-rtc false && timedatectl set-ntp true && \
 #            echo 'NTP=0.id.pool.ntp.org' >> /etc/systemd/timesyncd.conf && systemctl restart systemd-timesyncd"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            runAsUser: 0
        - name: increase-fd-ulimit
          image: busybox
          command: 
          - sh
          - -c
          - "ulimit -n 65536"
          securityContext:
            privileged: true
            runAsUser: 0
#        - name: enable-memory-lock
 #         image: busybox
  #        command:
   #       - sh
    #      - -c
     #     - "while true; do mmc=$(cat /etc/systemd/system/opensearch.service.d/override.conf); if [ ${mmc} -eq '[Service]\nLimitMEMLOCK=infinity' ]; then exit 0; else echo [Service]\nLimitMEMLOCK=infinity > /etc/systemd/system/opensearch.service.d/override.conf; fi; sleep 1; done"
    # " mkdir /etc/systemd/system/opensearch.service.d && echo '[Service]\nLimitMEMLOCK=infinity' > /etc/systemd/system/opensearch.service.d/override.conf"
      #    imagePullPolicy: IfNotPresent
       #   securityContext:
        #    privileged: true
         #   runAsUser: 0
          #volumeMounts:
          #- mountPath: /etc/systemd/system/opensearch.service.d/override.conf
           # name: memlock-config
      restartPolicy: Always
      volumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: opensearch-data
        - name: memlock-config
          configMap:
            name: memlock-config
