apiVersion: v1
kind: Service
metadata:
  labels:
    app: opensearch-node
  name: opensearch-node-service
spec:
  clusterIP: None
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    app: opensearch-node
status:
  loadBalancer: {}
