apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opensearch-logstash
  name: opensearch-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: opensearch-logstash
    spec:
      containers:
        - args:
            - -f
            - /usr/share/logstash/config/pipeline.conf
          env:
            - name: LOGSTASH_INTERNAL_PASSWORD
              value: ${LOGSTASH_INTERNAL_PASSWORD:-}
            - name: LS_JAVA_OPTS
              value: -Xmx256m -Xms256m
          image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.4.0
          name: opensearch-logstash
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config/pipeline.conf
              name: opensearch-log-pipeline
      restartPolicy: Always
      volumes:
      - name: opensearch-log-pipeline
        configMap:
          name: opensearch-log-pipeline
