apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
    part: spark-master
  name: spark-master-service
spec:
  clusterIP: None
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "7777"
      port: 7777
      targetPort: 7777
    - name: "7778"
      port: 7778
      targetPort: 7778
  selector:
    part: spark-master
status:
  loadBalancer: {}
