apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
    part: spark-history
  name: spark-history-service
spec:
  ports:
    - name: "18080"
      port: 18080
      targetPort: 18080
  selector:
    part: spark-history
