apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: spark
    part: spark-master
  name: spark-master
spec:
  serviceName: spark-master-service
  replicas: 1
  selector:
    matchLabels:
      part: spark-master
  template:
    metadata:
      labels:
        part: spark-master
    spec:
      containers:
        - args:
            - bash
            - -c
            - /opt/spark/sbin/start-master.sh
          env:
            - name: HADOOP_USER_NAME
              valueFrom:
                configMapKeyRef:
                  key: HADOOP_USER_NAME
                  name: spark-env
            - name: SPARK_APP_JAR_PATH
              valueFrom:
                configMapKeyRef:
                  key: SPARK_APP_JAR_PATH
                  name: spark-env
            - name: SPARK_DAEMON_MEMORY
              value: 1g
            - name: SPARK_EVENTLOG_DIR
              valueFrom:
                configMapKeyRef:
                  key: SPARK_EVENTLOG_DIR
                  name: spark-env
            - name: SPARK_HISTORY_OPTS
              valueFrom:
                configMapKeyRef:
                  key: SPARK_HISTORY_OPTS
                  name: spark-env
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_SCALA_VERSION
              value: "2.13"
          image: mataelang/spark:3.3.1-scala2.13
          name: spark-master
          ports:
            - containerPort: 8080
            - containerPort: 7077
          resources:
            limits:
              cpu: "1000m"
              memory: "1073741824"
            requests:
              cpu: "100m"
              memory: "1073741824"
          volumeMounts:
            - name: spark-conf
              mountPath: /opt/spark/conf/
              readOnly: true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      restartPolicy: Always
      volumes:
        - name: spark-conf
          configMap:
            name: spark-conf
