apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/test-default: "true"
        io.kompose.service: spark-master
    spec:
      containers:
        - args:
            - bash
            - -c
            - /opt/spark/sbin/start-master.sh
          env:
            - name: SPARK_DAEMON_MEMORY
              value: 1g
            - name: SPARK_MASTER_HOST
              value: spark-master
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_SCALA_VERSION
              value: "2.13"
          image: mataelang/spark:3.3.1-scala2.13
          name: spark-master
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1073741824"
            requests:
              cpu: "1"
              memory: "1073741824"
          volumeMounts:
            - mountPath: /opt/spark/conf/app.properties
              name: spark-master-hostpath0
            - mountPath: /opt/spark/conf/spark-defaults.conf
              name: spark-master-hostpath1
            - mountPath: /opt/spark/conf/log4j2.properties
              name: spark-master-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/xtrray/spark/test/conf/app.properties
          name: spark-master-hostpath0
        - hostPath:
            path: /home/xtrray/spark/test/conf/spark-defaults.conf
          name: spark-master-hostpath1
        - hostPath:
            path: /home/xtrray/spark/test/conf/log4j2.properties
          name: spark-master-hostpath2
status: {}
