apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: spark-submit-aggr
  name: spark-submit-aggr
spec:
  ports:
    - name: "7778"
      port: 7778
      targetPort: 7778
  selector:
    io.kompose.service: spark-submit-aggr
status:
  loadBalancer: {}
