apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-worker
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - args:
            - bash
            - -c
            - /opt/spark/sbin/start-worker.sh $()$(SPARK)_MASTER
          env:
            - name: SPARK_MASTER
              value: 'spark-master-service:7077'
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_SCALA_VERSION
              value: "2.13"
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_WORKER_DIR
              value: /opt/spark/work-dir
            - name: SPARK_WORKER_MEMORY
              value: 4G
          image: mataelang/spark:3.3.1-scala2.13
          name: spark-worker
          ports:
            - containerPort: 8081
            - containerPort: 4040
          resources: {}
          volumeMounts:
            - mountPath: /opt/spark/conf/app.properties
              name: spark-worker-hostpath0
            - mountPath: /opt/spark/conf/spark-defaults.conf
              name: spark-worker-hostpath1
            - mountPath: /opt/spark/conf/log4j2.properties
              name: spark-worker-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/skripsi/spark/app.properties
          name: spark-worker-hostpath0
        - hostPath:
            path: /home/skripsi/spark/spark-defaults.conf
          name: spark-worker-hostpath1
        - hostPath:
            path: /home/skripsi/spark/log4j2.properties
          name: spark-worker-hostpath2
