apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-submit-aggr
  name: spark-submit-aggr-service
spec:
  ports:
    - name: "7778"
      port: 7778
      targetPort: 7778
  selector:
    app: spark-submit-aggr
status:
  loadBalancer: {}
