apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark-historyserver
  name: spark-historyserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-historyserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spark-historyserver
    spec:
      containers:
        - args:
            - bash
            - -c
            - /opt/spark/sbin/start-history-server.sh
          env:
            - name: SPARK_DAEMON_MEMORY
              value: 1G
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_SCALA_VERSION
              value: "2.13"
          image: mataelang/spark:3.3.1-scala2.13
          name: spark-historyserver
          ports:
            - containerPort: 18080
          resources:
            limits:
              cpu: "1"
              memory: "1073741824"
            requests:
              cpu: "1"
              memory: "1073741824"
          volumeMounts:
            - mountPath: /opt/spark/conf/app.properties
              name: spark-historyserver-hostpath0
            - mountPath: /opt/spark/conf/spark-defaults.conf
              name: spark-historyserver-hostpath1
            - mountPath: /opt/spark/conf/log4j2.properties
              name: spark-historyserver-hostpath2
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /home/skripsi/spark/app.properties
          name: spark-historyserver-hostpath0
        - hostPath:
            path: /home/skripsi/spark/spark-defaults.conf
          name: spark-historyserver-hostpath1
        - hostPath:
            path: /home/skripsi/spark/log4j2.properties
          name: spark-historyserver-hostpath2
status: {}
