apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
    part: spark-submit
  name: spark-submit-service
spec:
  ports:
    - name: "7778"
      port: 7778
      targetPort: 7778
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    part: spark-submit
status:
  loadBalancer: {}
