apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark
    part: spark-worker
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      part: spark-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        part: spark-worker
    spec:
      containers:
        - args:
            - bash
            - -c
            - /opt/spark/sbin/start-worker.sh $()$(SPARK)_MASTER
          env:
            - name: SPARK_MASTER
              value: 'spark-master-service:7077'
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_SCALA_VERSION
              value: "2.13"
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_WORKER_DIR
              value: /opt/spark/work-dir
            - name: SPARK_WORKER_MEMORY
              value: 4G
          image: mataelang/spark:3.3.1-scala2.13
          name: spark-worker
          ports:
            - containerPort: 8081
            - containerPort: 4040
          resources: {}
          volumeMounts:
            - name: spark-config
              mountPath: /opt/spark/conf/
              subPath: conf
            - name: spark-env
              mountPath: /opt/spark/.env
              subPath: .env
      restartPolicy: Always
      volumes:
        - name: spark-config
          configMap:
            name: spark-config
        - name: spark-env
          configMap:
            name: spark-env
