apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spark
    part: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      part: spark-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        part: spark-master
    spec:
      containers:
        - args:
            - bash
            - -c
            - /opt/spark/sbin/start-master.sh
          env:
            - name: SPARK_DAEMON_MEMORY
              value: 1g
            - name: SPARK_MASTER_HOST
              value: spark-master
            - name: SPARK_MASTER_PORT
              value: "7077"
            - name: SPARK_MASTER_WEBUI_PORT
              value: "8080"
            - name: SPARK_NO_DAEMONIZE
              value: "true"
            - name: SPARK_SCALA_VERSION
              value: "2.13"
          image: mataelang/spark:3.3.1-scala2.13
          name: spark-master
          ports:
            - containerPort: 8080
            - containerPort: 7077
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: spark-config
              mountPath: /opt/spark/conf/
              subPath: conf
            - name: spark-env
              mountPath: /opt/spark/.env
              subPath: .env
      restartPolicy: Always
      volumes:
        - name: spark-config
          configMap:
            name: spark-config
        - name: spark-env
          configMap:
            name: spark-env
