apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
    part: spark-submit-enrich
  name: spark-submit-enrich-service
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    part: spark-submit-enrich
status:
  loadBalancer: {}
