apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
    part: spark-worker
  name: spark-worker-service
spec:
  clusterIP: None
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "4041"
      port: 4041
      targetPort: 4041
    #- name: "7777"
    # port: 7777
    #targetPort: 7777
    #- name: "7778"
    # port: 7778
    #targetPort: 7778
  selector:
    part: spark-worker
status:
  loadBalancer: {}
