apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-historyserver
  name: spark-historyserver-service
spec:
  ports:
    - name: "18080"
      port: 18080
      targetPort: 18080
  selector:
    app: spark-historyserver
status:
  loadBalancer: {}
