apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  serviceName: mosquitto-service
  selector:
    matchLabels:
      app: mosquitto
      tier: frontend
  template:
    metadata:
      labels:
        app: mosquitto
        tier: frontend
    spec:
      containers:
      - image: eclipse-mosquitto:latest
        name: mosquitto
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-persistent-storage
          mountPath: /mosquitto/data
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-password
          mountPath: /mosquitto/config/password_file
          subPath: password_file
      volumes:
      - name: mosquitto-persistent-storage
        persistentVolumeClaim:
          claimName: mosquitto-pvc
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
