apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  ports:
  - port: 1883
  selector:
    app: mosquitto
    tier: frontend
    type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mq-pv-claim
  labels:
    app: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
  labels:
    app: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/skripsi/mosquitto-pv"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mosquitto
        tier: frontend
    spec:
      containers:
      - image: eclipse-mosquitto:latest
        name: mosquitto
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-persistent-storage
          mountPath: /mosquitto/data
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: mosquitto-password
          mountPath: /mosquitto/config/password_file
          subPath: password_file
      volumes:
      - name: mosquitto-persistent-storage
        persistentVolumeClaim:
          claimName: mq-pv-claim
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
      - name: mosquitto-password
        configMap:
          name: mosquitto-password
