apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-password
  labels:
    app: mosquitto
data:
  password_file.txt: |
    mataelang:$6$JnLlFKHZtSPEiC3f$gu9XJwsSekVRUaymIM5/FyqPz48M6GEajwg0kpN2sOfPSCiEBeLbSRf5aoF4mDDcn51qBqgpzX8OUcI/OtMjlA==
