apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml --volumes hostPath
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/test-default: "true"
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  containers:
    - image: eclipse-mosquitto:2.0.15
      name: mosquitto
      ports:
        - containerPort: 1883
      resources:
        limits:
          cpu: 500m
          memory: "536870912"
        requests:
          cpu: 250m
          memory: "134217728"
      volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          name: mosquitto-hostpath0
        - mountPath: /mosquitto/config/password_file
          name: mosquitto-hostpath1
        - mountPath: /mosquitto/data
          name: mosquitto-data
  restartPolicy: OnFailure
  volumes:
    - hostPath:
        path: /home/xtrray/mosquitto/test/mosquitto.conf
      name: mosquitto-hostpath0
    - hostPath:
        path: /home/xtrray/mosquitto/test/mosquitto_passwd
      name: mosquitto-hostpath1
    - hostPath:
        path: /home/xtrray/mosquitto/test
      name: mosquitto-data
status: {}
