apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-data
  labels:
    app: mosquitto
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/skripsi/mosquitto-pv"
