apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  labels:
    app: hdfs-namenode
spec:
  serviceName: hdfs-namenode-service
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
        - name: hdfs-namenode
          image: quay.io/ferdyf78/hdfs-k8s:namenode-openjdk
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
            - containerPort: 9870
          volumeMounts:
            - name: hdfs-conf
              mountPath: "/usr/local/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
