apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode-service
  labels:
    app: hdfs-datanode
spec:
  ports:
    - name: "9864"
      port: 9864
      targetPort: 9864
  clusterIP: None
  selector:
    app: hdfs-datanode
