apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
  labels:
    app: namenode
spec:
  serviceName: namenode-service
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: quay.io/ferdyf78/hdfs-k8s:namenode
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
            - containerPort: 9870
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /app/name
          volumeMounts:
            - name: hadoopconf
              mountPath: "/usr/local/hadoop/etc/hadoop"
              readOnly: true
      #            - name: nn-pvc
      #             mountPath: "/app/name"
      volumes:
        - name: hadoopconf
          configMap:
            name: hadoopconf
#        - name: nn-pvc
#         persistentVolumeClaim:
#          claimName: nn-pvc
