apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  serviceName: hdfs-datanode-service
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: quay.io/ferdyf78/hdfs-k8s:datanode-openjdk
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9864
          #env:
          # - name: ENSURE_NAMENODE_DIR
          #  value: /app/data
          volumeMounts:
            - name: hdfs-conf
              mountPath: "/usr/local/hadoop/etc/hadoop/"
              readOnly: true
      #         - name: dn-pvc
      #          mountPath: "/app/data"
      volumes:
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
  #       - name: dn-pvc
  #        persistentVolumeClaim:
  #         claimName: dn-pvc
