apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  labels:
    app: hdfs-datanode
spec:
  serviceName: hdfs-datanode-service
  replicas: 1
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: quay.io/ferdyf78/hdfs-k8s:datanode-openjdk
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9864
          volumeMounts:
            - name: hdfs-conf
              mountPath: "/usr/local/hadoop/etc/hadoop/"
              readOnly: true
      volumes:
        - name: hdfs-conf
          configMap:
            name: hdfs-conf
