apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  serviceName: datanode-service
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode
    spec:
      containers:
        - name: datanode
          image: quay.io/ferdyf78/hdfs-k8s:datanode
          #imagePullPolicy: Always
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9864
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /app/data
          volumeMounts:
            - name: hadoopconf
              mountPath: "/usr/local/hadoop/etc/hadoop/"
              readOnly: true
      #         - name: dn-pvc
      #          mountPath: "/app/data"
      volumes:
        - name: hadoopconf
          configMap:
            name: hadoopconf
  #       - name: dn-pvc
  #        persistentVolumeClaim:
  #         claimName: dn-pvc
