apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode-service
  labels:
    app: hdfs-namenode
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9870"
      port: 9870
      targetPort: 9870
  clusterIP: None
  selector:
    app: hdfs-namenode
