apiVersion: v1
kind: Service
metadata:
  name: namenode-service
  labels:
    app: namenode
spec:
  ports:
    - port: 50070
      name: web
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9870"
      port: 9870
      targetPort: 9870
  clusterIP: None
  selector:
    app: namenode
