apiVersion: v1
kind: Service
metadata:
  labels:
    app: control-center
  name: control-center-service
spec:
  ports:
    - name: "9021"
      port: 9021
      targetPort: 8080
  selector:
    app: control-center
status:
  loadBalancer: {}
