apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092,EXTERNAL://kafka-service:9093
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "536870912"
            - name: KAFKA_LOG_RETENTION_MS
              value: "86400000"
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "536870912"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 'zookeeper-service:2181'
          image: confluentinc/cp-kafka:7.3.0
          name: kafka-broker
          ports:
            - containerPort: 9093
          resources:
            limits:
              cpu: 500m
              memory: "2147483648"
            requests:
              cpu: 250m
              memory: "1073741824"
          volumeMounts:
            - mountPath: /var/lib/kafka/data
              name: kafka-data
      restartPolicy: Always
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-data
